spring:
  application:
    name: DesafioTecnico-NgBilling

  datasource:
    url: jdbc:h2:mem:ngbillingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    user: sa
    password: